/*
    majere addition (ingredient finder) -- GENERATED by tools/gen_ingredient_table.py from a table of the
    vanilla game's restocking ingredient sellers (Morrowind, Tribunal, Bloodmoon).
    Vanilla baseline: the server may move or change vendors; the finder adds live cell data on top.
*/

#include "ingredientdata.hpp"

namespace MWGui
{
    const std::vector<IngredientDef>& ingredientTable()
    {
        static const std::vector<IngredientDef> table = {
            { "Saltrice", 0, { "ingred_saltrice_01" }, { {"Chaplain Ogrul", "Gnisis, Fort Darius"}, {"Scelian Plebo", "Sadrith Mora, Wolverine Hall: Imperial Shrine"}, {"Felara Andrethi", "Tel Aruhn, Tower Living Quarters"}, {"Tivam Sadri", "Holamayan Monastery"}, {"Eldrilu Dalen", "Vos, Vos Chapel"}, {"Sedris Omalen", "Maar Gan, Outpost"}, {"Guls Llervu", "Ald-ruhn, Guls Llervu's House"}, {"J'Rasha", "Vivec, J'Rasha: Healer"}, {"Vaval Selas", "Vivec, St. Olms Temple"}, {"Llarara Omayn", "Balmora, Temple"}, {"Ra'Tesh", "Mournhold, The Winged Guar"} } },
            { "Marshmerrow", 0, { "ingred_marshmerrow_01" }, { {"Chaplain Ogrul", "Gnisis, Fort Darius"}, {"Scelian Plebo", "Sadrith Mora, Wolverine Hall: Imperial Shrine"}, {"Andil", "Tel Vos, Services Tower"}, {"Felara Andrethi", "Tel Aruhn, Tower Living Quarters"}, {"Milar Maryon", "Tel Vos, Services Tower"}, {"Danoso Andrano", "Ald-ruhn, Temple"}, {"Ygfa", "Pelagiad, Fort Pelagiad"}, {"J'Rasha", "Vivec, J'Rasha: Healer"}, {"Dralval Andrano", "Balmora, Temple"} } },
            { "Chokeweed", 0, { "ingred_chokeweed_01" }, { {"Scelian Plebo", "Sadrith Mora, Wolverine Hall: Imperial Shrine"}, {"Ygfa", "Pelagiad, Fort Pelagiad"}, {"J'Rasha", "Vivec, J'Rasha: Healer"}, {"Vaval Selas", "Vivec, St. Olms Temple"}, {"Telis Salvani", "Balmora, Temple"}, {"Felara Andrethi", "Tel Aruhn, Tower Living Quarters"} } },
            { "Hackle-Lo Leaf", 0, { "ingred_hackle-lo_leaf_01" }, { {"Anis Seloth", "Sadrith Mora, Anis Seloth: Alchemist"}, {"Gils Drelas", "Tel Branora, Upper Tower: Therana's Chamber"}, {"Tivam Sadri", "Holamayan Monastery"}, {"Daynali Dren", "Tel Mora, Lower Tower"}, {"Mehra Drora", "Gnisis, Temple"}, {"Sedris Omalen", "Maar Gan, Outpost"}, {"Garas Seloth", "Vivec, Telvanni Alchemist"}, {"Llarara Omayn", "Balmora, Temple"}, {"Mehra Helas", "Mournhold, Temple Courtyard"} } },
            { "Frost Salts", 1, { "ingred_frost_salts_01" }, { {"Ulumpha gra-Sharob", "Gnisis, Fort Darius"}, {"Anis Seloth", "Sadrith Mora, Anis Seloth: Alchemist"}, {"Nalcarya of White Haven", "Balmora, Nalcarya of White Haven: Fine Alchemist"}, {"Daynali Dren", "Tel Mora, Lower Tower"}, {"Craetia Jullalian", "Vivec, Guild of Mages"}, {"Gils Drelas", "Tel Branora, Upper Tower: Therana's Chamber"} } },
            { "Fire Petal", 1, { "ingred_fire_petal_01" }, { {"Irna Maryon", "Tel Aruhn, Tower Entry"}, {"Mehra Drora", "Gnisis, Temple"}, {"Pierlette Rostorard", "Sadrith Mora, Pierlette Rostorard: Apothecary"}, {"Cocistian Quaspus", "Buckmoth Legion Fort, Interior"}, {"Somutis Vunnis", "Moonmoth Legion Fort, Interior"}, {"Galuro Belan", "Vivec, Telvanni Apothecary"}, {"Mehra Helas", "Mournhold, Temple Courtyard"} } },
            { "Ash Salts", 1, { "ingred_ash_salts_01" }, { {"Scelian Plebo", "Sadrith Mora, Wolverine Hall: Imperial Shrine"}, {"Somutis Vunnis", "Moonmoth Legion Fort, Interior"}, {"Relms Gilvilo", "Vivec, Redoran Temple Shrine"}, {"Tivam Sadri", "Holamayan Monastery"}, {"Eldrilu Dalen", "Vos, Vos Chapel"}, {"Telis Salvani", "Balmora, Temple"}, {"Folvys Andalor", "Ald-ruhn, Temple"} } },
            { "Belladonna", 1, { "ingred_belladonna_01", "ingred_belladonna_02" }, {  } },
            { "Moon Sugar", 2, { "ingred_moon_sugar_01" }, {  } },
            { "Pearl", 2, { "ingred_pearl_01" }, { {"Anis Seloth", "Sadrith Mora, Anis Seloth: Alchemist"}, {"Nalcarya of White Haven", "Balmora, Nalcarya of White Haven: Fine Alchemist"}, {"Gils Drelas", "Tel Branora, Upper Tower: Therana's Chamber"}, {"Danoso Andrano", "Ald-ruhn, Temple"}, {"Peragon", "Moonmoth Legion Fort, Interior"}, {"Jolda", "Tel Mora, Jolda: Apothecary"}, {"Craetia Jullalian", "Vivec, Guild of Mages"}, {"Garas Seloth", "Vivec, Telvanni Alchemist"} } },
            { "Bungler's Bane", 2, { "ingred_bc_bungler's_bane" }, { {"Danoso Andrano", "Ald-ruhn, Temple"}, {"Tusamircil", "Sadrith Mora, Wolverine Hall: Mage's Guild"}, {"Jolda", "Tel Mora, Jolda: Apothecary"}, {"Ganalyn Saram", "Vivec, Hlaalu Alchemist"}, {"Dralval Andrano", "Balmora, Temple"} } },
        };
        return table;
    }
}
